# Background nebula detail.
[[layers]]
type = "noise"
seed = 7832
innercolor = "#A020E1"
outercolor = "#490070"
noise_type = "ridged"
frequency = "4"
octaves = 8
power = "0.25"
threshold = "0.5"

# Mask background nebula.
[[layers]]
type = "noise"
seed = 3551
noise_type = "fbm"
innercolor = "#000000"
outercolor = "#000000"
destfactor = "SrcAlpha"
octaves = 4
persistence = "0.5"
power = "0.35"
lacunarity = "1.5"
frequency = "3"
threshold = "0.2"

# Dim background nebula stars.
[[layers]]
type = "points"
seed = 3909
closecolor = "#414562"
count = 750
mask = true
masknoise_type = "fbm"
maskoctaves = 4
maskpower = "0.35"
maskfrequency = "1.0"
maskthreshold = "0.45"
maskseed = 3551

# Bright background nebula stars.
[[layers]]
type = "points"
closecolor = "#7E86BF"
count = 25
seed = 3472
mask = true
masknoise_type = "fbm"
maskoctaves = 4
maskpower = "0.35"
maskfrequency = "1.0"
maskthreshold = "0.6"
maskseed = 3551

# Bright background nebula stars, dim edge.
[[layers]]
type = "points"
closecolor = "#3D415C"
size = 2
count = 25
seed = 3472
mask = true
masknoise_type = "fbm"
maskoctaves = 4
maskpower = "0.35"
maskfrequency = "1.0"
maskthreshold = "0.6"
maskseed = 3551