# Background nebula detail.
[[layers]]
type = "noise"
seed = 7832
innercolor = "#A020E1"
outercolor = "#490070"
noise_type = "ridged"
frequency = "4"
octaves = 8
power = "0.25"
threshold = "0.5"

# Mask background nebula.
[[layers]]
type = "noise"
noise_type = "fbm"
innercolor = "#000000"
outercolor = "#000000"
destfactor = "SrcAlpha"
seed = 3551
octaves = 4
power = "0.35"
lacunarity = "1.5"
frequency = "3"
threshold = "0.0"

# Dim background nebula stars.
[[layers]]
type = "points"
seed = 3909
closecolor = "#414562"
count = 750
mask = true
masknoise_type = "fbm"
maskoctaves = 4
maskpersistence = "0.5"
maskpower = "0.35"
masklacunarity = "1.5"
maskfrequency = "3"
maskthreshold = "0.0"
maskseed = 3551

# Bright background nebula stars.
[[layers]]
type = "points"
closecolor = "#7E86BF"
count = 750
seed = 3472
mask = true
masknoise_type = "fbm"
maskoctaves = 4
maskpersistence = "0.5"
maskpower = "0.35"
masklacunarity = "1.5"
maskfrequency = "3"
maskthreshold = "0.37"
maskseed = 3551

# Bright background nebula stars, dim edge.
[[layers]]
type = "points"
closecolor = "#3D415C"
size = 2
count = 750
seed = 3472
mask = true
masknoise_type = "fbm"
maskoctaves = 4
maskpersistence = "0.5"
maskpower = "0.35"
masklacunarity = "1.5"
maskfrequency = "3"
maskthreshold = "0.37"
maskseed = 3551
